# docker-compose setup for quick preview.
# Use dev.docker-compose.yaml if you want to debug a local build.
# Use the helm chart if you want to deploy in production.
version: "2.2"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.2
    entrypoint: [etcd]
    command:
      - -name=main
      - -advertise-client-urls=http://etcd:2379
      - -listen-client-urls=http://0.0.0.0:2379
      - -initial-advertise-peer-urls=http://etcd:2380
      - -listen-peer-urls=http://0.0.0.0:2380
      - -initial-cluster-state=new
      - -initial-cluster=main=http://etcd:2380
      - -initial-cluster-token=etcd-cluster-1
      - -data-dir=/var/run/etcd/default.etcd
    volumes:
      - etcd:/var/run/etcd/default.etcd
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms128m -Xmx128m"
    mem_limit: 536870912
    volumes:
      - es:/usr/share/elasticsearch/data
  jaeger-query:
    image: jaegertracing/jaeger-query:1.42
    environment:
      GRPC_STORAGE_SERVER: kelemetry:17271
      SPAN_STORAGE_TYPE: grpc-plugin
    ports:
      - 0.0.0.0:16686:16686
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.42
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://es:9200
      ES_INDEX_PREFIX: kelemetry
  kelemetry:
    build: .

volumes:
  etcd: {}
  es: {}
