---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-consumer
  labels: {{ include "kelemetry.consumer-labels" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Name}}-consumer
  labels: {{ include "kelemetry.consumer-labels" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Release.Name}}-consumer
subjects:
  - kind: ServiceAccount
    name: {{.Release.Name}}-consumer
    namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Release.Name}}-consumer
  labels: {{ include "kelemetry.consumer-labels" . }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
