{{- range .Values.multiCluster.clusters }}
{{- if .kubeconfig.type | eq "literal" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mnt-cluster-kubeconfig-{{.name}}
data:
  kubeconfig: {{ b64enc .kubeconfig.literal | toJson }}
{{- end }}
{{- end }}
