[[metrics]]
name = "baseline"
quantifier = "mq_latency"
tags = ["cluster"]


[[metrics]]
name = "errors_by_user"
quantifier = "request_count"
tags = ["username", "cluster", "group", "resource", "verb", "code", "errorReason"]
    [[metrics.filters]]
    tag = "code"
    oneOf = ["[45].."]
    isRegex = true

[[metrics]]
name = "cache_penetrations"
quantifier = "request_count"
tags = ["username", "cluster", "group", "resource", "verb"]
    [[metrics.filters]]
    tag = "code"
    oneOf = ["200"]
    [[metrics.filters]]
    tag = "resourceVersion"
    oneOf = ["Empty"]
    [[metrics.filters]]
    tag = "verb"
    oneOf = ["list", "get"]

[[metrics]]
name = "list_timeout"
quantifier = "request_latency_ratio"
tags = ["username", "cluster", "group", "resource"]
    [[metrics.filters]]
    tag = "code"
    oneOf = ["200"]
    [[metrics.filters]]
    tag = "verb"
    oneOf = ["list"]

[[metrics]]
name = "watch_error"
quantifier = "request_latency_ratio"
tags = ["username", "cluster", "group", "resource"]
    [[metrics.filters]]
    tag = "code"
    oneOf = ["200"]
    [[metrics.filters]]
    tag = "verb"
    oneOf = ["watch"]
