name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Run unit tests
        run: make test

  lint:
    name: golangci-lint
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m
          only-new-issues: true
