name: Publish helm chart

on:
  push:
    tags: "*"
    branches: ["main"]

jobs:
  publish-chart:
    name: Build helm chart
    runs-on: [ubuntu-20.04]
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker login for ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set image tag for release
        id: tag-name
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - run: helm package charts/kelemetry --app-version="${IMAGE_TAG}" --version="${{steps.tag-name.outputs.{IMAGE_TAG}}}" -d output
      - run: helm push output/kelemetry-chart-${IMAGE_TAG}.tgz oci://ghcr.io/kubewharf
